### ISSUE TITLE
Error in parsing outfolder

### ISSUE THREAD

**Issue by tleonardi** [a-slide/NanopolishComp#12]
If the outfolder is a relative path and doesn't end with a '/', the following error is raise:
```
Traceback (most recent call last):
  File "/usr/local/bin/NanopolishComp", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/NanopolishComp/__main__.py", line 65, in main
    args.func(args)
  File "/usr/local/lib/python3.5/dist-packages/NanopolishComp/__main__.py", line 80, in Eventalign_collapse_main
    quiet = args.quiet)
  File "/usr/local/lib/python3.5/dist-packages/NanopolishComp/Eventalign_collapse.py", line 82, in __init__
    raise IOError ("Cannot write output file in indicated folder. Create the output folder if it does not exist yet")
OSError: Cannot write output file in indicated folder. Create the output folder if it does not exist yet
```

The solution might be to just append a slash to the string, since a double slash shouldn't cause any problem.

**Comment by a-slide** [comment]
I crumps. Doesn't seem hard to fix. I will do that  ASAP.

**Comment by a-slide** [comment]
Fixed
